### ISSUE TITLE
Unit tests in "test_sites_routes.py" return false positives

### ISSUE THREAD

**Issue by lorenzo-pasa** [cuducos/findaconf#12]
Almost all test methods in [test_sites_routes.py](https://github.com/cuducos/findaconf/blob/user-roles/findaconf/tests/test_site_routes.py) execute their checks and assertions only when the `if valid_providers:` condition is fulfilled.

But, at this moment, in 8 out of 12 tests present in the file, that condition is not fulfilled, and without an `else:` option, the tests simply don't do anything, neither raising assertion errors, thus they are all evaluated as "passed".

-
A simple way to reproduce this bug in the aforementioned file, is to add this lines
```
else:
    self.assertEqual(1,2,'valid_providers: {}'.format(valid_providers))
```
at the end of each method that uses the `if valid_providers:` statement.

-
**Side note:** this bug could be hidden also in other test files. A wider and deeper search is *strongly* required.

**Comment by lorenzo-pasa** [comment]
The list of valid providers is retrieved by the `OAuthProvider.get_slugs()` method, defined [here](https://github.com/cuducos/findaconf/blob/user-roles/findaconf/helpers/providers.py#L66).

Maybe that method is the cause behind the list being empty during the tests.

**Comment by cuducos** [comment]
This method `OAuthProvider.get_slugs()` depends on having _valid_ providers set in the `.env` file ([here it loads the config var](https://github.com/cuducos/findaconf/blob/user-roles/findaconf/helpers/providers.py#L30)).

Maybe the best thing would be to create a mock `app.config['OAUTH_CREDENTIALS']` in the [tests/config.py](https://github.com/cuducos/findaconf/blob/user-roles/findaconf/tests/config.py).

Gonna (try to) solve that later today!
